### ISSUE TITLE
Duplicate data to csv function

### ISSUE THREAD

**Issue by dsgorthy** [callie-jones/bits-weather-dashboard#12]

**Comment by dsgorthy** [comment]
Currently looking to replicating data that is written to MongoDB as a flat csv file

**Comment by dsgorthy** [comment]
Currently only implemented in the temperature driver, awaiting code review and possibly live reading testing

**Comment by dsgorthy** [comment]
@JackDinkel specifically check the creating a new file if it does not exist, this may cause on issue

**Comment by JackDinkel** [comment]
Everything looks good. The code functions as I would expect and I saw no bugs. It creates the file if it doesn't exist, and appends if it does.
