### ISSUE TITLE
Temperature Sensor Integration

### ISSUE THREAD

**Issue by dsgorthy** [callie-jones/bits-weather-dashboard#4]
Description: Connect temperature sensor to BITS

**Comment by JackDinkel** [comment]
Derek and Kelsey's exec and file reading code works great!

I have added a new directory called `sensor_drivers` that will house our driver software. Inside is a directory called `thermometer` that contains the driver software for the thermometer. See the README inside the directory for compilation instructions.

The compiled binary is a file called `pcsensor`. That is the binary we want to exec in our code.

I have also added some basic string parsing to the code. More work to be done!

**Comment by dsgorthy** [comment]
Basic code structure in place, we still need to test to make sure that the sensor can be plugged in and the values can be read into the database. Basic functionality in place, but custom code will need to be written to address this problem. I will be working with @callie-jones and @JackDinkel to get sensor hooked up and integrated.

**Comment by JackDinkel** [comment]
I have solved my issue reading from the sensor discussed in the team meeting as part of #10. Hopefully that ticket will allow me to replace the `pcsensor` file with a custom driver.

**Comment by JackDinkel** [comment]
The current `pcsensor` driver for the temperature sensor works great.
In the future, the generic sensor development will be tracked in #10
