### ISSUE TITLE
Frontend interfacing - Placeholder for tabs we will implement, show barebones measurements and a bit fancier display

### ISSUE THREAD

**Issue by sanoff** [callie-jones/bits-weather-dashboard#9]
Show current temperatures, barometers, weight sensor. Push MongoDB connection to interface for each, but use placeholder for sensors that aren't ready. Include tabs for graphs, current temperature, and temperature history for past 24 hours.

**Comment by dsgorthy** [comment]
Branch code from master, create a front-end branch, pull all changed go into this branch

**Comment by kedo8480** [comment]
Front end is now static, no data pulled yet, but outline is there!

**Comment by dsgorthy** [comment]
Template is done, now need to pull in live readings. Work on this will be tracked under #13 . Closing out issue.
